added loadSiteConfig(): makes sure general settings are loaded as ENV vars

diff --git a/services/deploytools b/services/deploytools
--- a/services/deploytools
+++ b/services/deploytools
@@ -22,6 +22,34 @@ checkVars()
     done
 }
 
+loadSiteConfig()
+{
+    local fx="loadSiteConfig():"
+    if [ -z "$SC_SITECONFIG" ]; then
+        SC_SITECONFIG="$scriptdir/siteconfig"
+        echo "$fx SC_SITECONFIG is not set, using '$SC_SITECONFIG'."
+    fi
+    export SC_SITECONFIG
+    if [ ! -d "$SC_SITECONFIG" ]; then
+        echo "$fx site config path does not exist, creating it: '$SC_SITECONFIG'!"
+        # generate some passwords before starting any services
+        mkdir -p "$SC_SITECONFIG"
+    fi
+    local fn="$SC_SITECONFIG/general.rc"
+    if [ ! -f "$fn" ]; then
+        echo "$fx WARNING: Missing general settings in '$fn'!"
+        echo "    -> Creating a template, please fill it out."
+        cat > "$fn" << EOF
+export DOMAINBASE=
+export REGISTRY_PORT=31000
+export REGISTRY_NAME=img.\$DOMAINBASE
+export CERT_PATH_PUB=
+export CERT_PATH_PRIV=
+EOF
+    fi
+    . "$fn"
+}
+
 getHostAddr()
 {
     local devpath devname hostaddr
@@ -62,14 +90,14 @@ injectEnvConfig()
 update_envfiles()
 {
     local fx="update_envfiles():"
-    checkVars SITECONFIG || return
+    checkVars SC_SITECONFIG || return
     local service; service="$1"
     [ -z "$service" ] && (echo "$fx No service name provided! Nothing to do." && return)
     local targetDir; targetDir="$service/$2"
     [ -d "$targetDir" ] || (echo "$fx Target dir '$targetDir' not found! Nothing to do." && return)
     # make sure we're in the correct path
     [ -d "$service" ] || (echo "$fx Service path '$service' not found!" && return)
-    local src; src="$SITECONFIG/$service"
+    local src; src="$SC_SITECONFIG/$service"
     [ -d "$src" ] || (echo "$fx Service path '$src' not found!" && return)
     if [ "$service" = "catamel" ]; then
         # put first-time config files in place to get system running at all
@@ -88,9 +116,9 @@ reset_envfiles()
 
 create_dbuser()
 {
-    checkVars SITECONFIG || return
+    checkVars SC_SITECONFIG || return
     local service="$2"
-    local svcjs="$SITECONFIG/mongodb/${service}.js"
+    local svcjs="$SC_SITECONFIG/mongodb/${service}.js"
     local rootpwd; rootpwd="$(kubectl get secret -n dev local-mongodb \
         -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)"
     local mongopod; mongopod=$(kubectl get pods --all-namespaces | awk '/mongo/ {print $2}')
@@ -105,7 +133,7 @@ create_dbuser()
 
 delete_dbuser()
 {
-    checkVars SITECONFIG || return
+    checkVars SC_SITECONFIG || return
     local service="$1"
     local username="$2"
     local rootpwd; rootpwd="$(kubectl get secret -n dev local-mongodb \
@@ -116,7 +144,7 @@ delete_dbuser()
         return
     fi
     local dbname; dbname="$(awk '/db:/ {gsub("^\"|\"$,?","",$2); print $2}' \
-        "$SITECONFIG/mongodb/${service}.js")"
+        "$SC_SITECONFIG/mongodb/${service}.js")"
     kubectl -n dev exec -i $mongopod \
         -- mongo $dbname -u root -p "$rootpwd" --authenticationDatabase admin -eval "db.dropUser(\"$username\")"
 }
