deploytools: registryPush helper added

diff --git a/services/deploytools b/services/deploytools
--- a/services/deploytools
+++ b/services/deploytools
@@ -16,6 +16,22 @@ if ! cmdExists docker; then
     DOCKER_PUSH="buildah push"
 fi
 
+registryPush()
+{
+    local i=0;
+    local cmd="$DOCKER_PUSH $*"
+    while ! (echo "$cmd"; eval "$cmd"); do
+        if [ "$i" -eq 8 ]; then
+            echo "Push failed $i times, giving up."
+            break
+        fi
+        delay="$(python -c "print(5*2**$i)")"
+        echo "Failed to push, waiting $delay s before trying again ..."
+        sleep $delay
+        i=$((i+1))
+    done
+}
+
 getImageTag()
 {
     # <timestamp>_<git commit>
