registry gets credentials from siteconfig; moved generator call to siteconfig

diff --git a/services/deploytools b/services/deploytools
--- a/services/deploytools
+++ b/services/deploytools
@@ -39,10 +39,13 @@ loadSiteConfig()
     if [ ! -f "$fn" ]; then
         echo "$fx WARNING: Missing general settings in '$fn'!"
         echo "    -> Creating a template, please fill it out."
+        command -v apg || (echo "Password generator 'apg' required! Giving up."; return)
         cat > "$fn" << EOF
 export DOMAINBASE=
 export REGISTRY_PORT=31000
 export REGISTRY_NAME=img.\$DOMAINBASE
+export REGISTRY_USER=foo
+export REGISTRY_PASS=$(apg -m 17 -n1 -M NCL)
 export CERT_PATH_PUB=
 export CERT_PATH_PRIV=
 export SC_MEDIA_PATH=
